name: FaunaReborn
description: '${description}'
version: '${version}'

main: io.github.devskycore.faunareborn.core.FaunaRebornPlugin
api-version: '1.21'
folia-supported: true
load: POSTWORLD

authors: [ DevSkyCore ]
website: https://github.com/devskycore

commands:
  fauna:
    description: Main command for FaunaReborn.
    aliases: [ faunareborn, fr ]
    permission: fauna.command.help
    usage: "/fauna help [page|admin|permissions|query]"

permissions:
  fauna.*:
    description: Grants access to all FaunaReborn commands.
    default: op
    children:
      fauna.admin: true
      fauna.command.help: true
      fauna.command.help.admin: true
      fauna.command.version: true
      fauna.command.about: true
      fauna.command.entities: true
      fauna.command.reload: true
      fauna.command.gui: true
      fauna.command.lang: true

  fauna.admin:
    description: Grants access to FaunaReborn administrative commands.
    default: op
    children:
      fauna.command.reload: true
      fauna.command.gui: true
      fauna.command.lang: true

  fauna.command.help:
    description: Allows viewing the FaunaReborn help menu.
    default: true

  fauna.command.help.admin:
    description: Allows viewing administrative commands in /fauna help.
    default: op

  fauna.command.version:
    description: Allows viewing the FaunaReborn version information.
    default: true

  fauna.command.about:
    description: Allows viewing information about FaunaReborn.
    default: true

  fauna.command.entities:
    description: Allows viewing supported FaunaReborn entities.
    default: true

  fauna.command.reload:
    description: Allows reloading the FaunaReborn configuration.
    default: op

  fauna.command.gui:
    description: Allows opening the FaunaReborn admin GUI.
    default: op

  fauna.command.lang:
    description: Allows opening the language selector and changing language at runtime.
    default: op
