name: FaunaReborn
description: '${description}'
version: '${version}'
main: io.github.devskycore.faunareborn.core.FaunaRebornPlugin
api-version: '1.21'

authors: [ DevSkyCore ]
website: https://github.com/devskycore

commands:
  fauna:
    description: Main command for FaunaReborn.
    aliases: [ faunareborn, fr ]
    permission: fauna.command.help
    usage: "/fauna help [page|admin|permissions|query]"
